// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQrHgwplQII6SoScxf7Xen2THGZosMWNs',
    appId: '1:384511522400:web:8ca1b28e7878643645b505',
    messagingSenderId: '384511522400',
    projectId: 'fir-project-a504c',
    authDomain: 'fir-project-a504c.firebaseapp.com',
    storageBucket: 'fir-project-a504c.firebasestorage.app',
    measurementId: 'G-L9NGXHTBKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnoIXYsYVI395_iFhiKiwkwgE_Nq1BIWE',
    appId: '1:384511522400:android:13fc5ae57a373d9e45b505',
    messagingSenderId: '384511522400',
    projectId: 'fir-project-a504c',
    storageBucket: 'fir-project-a504c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA968fXloRqmh-Mp7T5_JYhwBhzl-o-zyA',
    appId: '1:384511522400:ios:3899632fe63411d345b505',
    messagingSenderId: '384511522400',
    projectId: 'fir-project-a504c',
    storageBucket: 'fir-project-a504c.firebasestorage.app',
    iosClientId: '384511522400-gjqj6qvh1391nkrg52nrlspd1c5pse4l.apps.googleusercontent.com',
    iosBundleId: 'com.afriyuan.afriyuanMobile',
  );
}
